apiVersion: v1
kind: Pod
metadata:
  name: my-web
  labels:
    env : prod
    app : main
    owner: dan
spec:
  containers:
  - name: container-apache
    image: nginx:latest
    ports:
    - containerPort: 80
    
